@define[PPT_PAGE_TITLE:Louisa TSA Home]
@define[PPT_STYLE_SHEET:"home.css"]
@define[PPT_HOME_ACTIVE:"active"]
@define[PPT_ABOUT_ACTIVE:""]
@define[PPT_COMPETITIONS_ACTIVE:""]
@define[PPT_EVENTS_ACTIVE:""]
@define[PPT_MEMBERS_ACTIVE:""]
@define[PPT_PAGE_CONTENT:
@include[../pages/home_c.html]
]
@include[../templates/page_template.html]