@define[PPT_PAGE_TITLE:Louisa TSA Members]
@define[PPT_STYLE_SHEET:"members.css"]
@define[PPT_HOME_ACTIVE:""]
@define[PPT_ABOUT_ACTIVE:""]
@define[PPT_COMPETITIONS_ACTIVE:""]
@define[PPT_EVENTS_ACTIVE:""]
@define[PPT_MEMBERS_ACTIVE:"active"]
@define[PPT_PAGE_CONTENT:
@include[../pages/members_c.html]
]
@include[../templates/page_template.html]